{
 "title": "Environment Monitor",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"outdoor\")\n    |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  },
  {
   "title": "External Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"outdoor\")\n    |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Barometric Pessure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "Atmosferic Pressure (hPa)",
   "type": "timeseries",
   "description": "Atmosferic pressure in the past 7 days",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  },
  { "title": "Indoor Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "description": "Temperature in the last 7 days",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Indoor Humidity",
   "type": "timeseries",
   "description": "Humidity in the past 7 days",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  },
  { "title": "Outdoor Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"outdoor\")\n    |> filter(fn: (r) => r._field == \"temperature\")"
    },
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Outside Humidity vs Inside Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"outdoor\")\n    |> filter(fn: (r) => r._field == \"humidity\")"
    },
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  },
  { "title": "Radiation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\" and r.asset == \"j305\")\n    |> filter(fn: (r) => r._field == \"cpm\")"
    }
   ]
  },
  {
   "title": "uSv per Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\" and r.asset == \"j305\")\n    |> filter(fn: (r) => r._field == \"usv_h\")"
    }
   ]
  },
  {
   "title": "CPM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\" and r.asset == \"j305\")\n    |> filter(fn: (r) => r._field == \"cpm\")"
    }
   ]
  },
  {
   "title": "uSv per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "targets": [
    {
     "query": "from(bucket: \"lizard\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"environment\" and r.location == \"indoor\" and r.asset == \"j305\")\n    |> filter(fn: (r) => r._field == \"usv_h\")"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "description": "CPU Temperatures over the past week",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"hardware\" and r.asset == \"nezarr\")\n    |> filter(fn: (r) => r._field == \"cpu_temp\")"
    },
    {
     "query": "from(bucket: \"hardware\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"hardware\" and r.asset == \"pihole\" and r.location == \"indoor\")\n    |> filter(fn: (r) => r._field == \"cpu_temp\")"
    }
   ]
  }
 ]
}